NumPy 2
SciTools/python-stratify pull request #292
Opened 2024-12-04 11:48 UTC by HGWright

## 🚀 Pull Request

### Description

---

We want to move to NumPy version 2, this updates the lockfiles to use it and we can fix the tests later.

2025-02-07 13:16 UTC, bjlittle commented
@HGWright Did you want to resolve the conflicts?

2025-02-07 13:23 UTC, bjlittle requested changes
@HGWright Some comments to service 👍

2025-02-07 13:23 UTC, bjlittle commented on .github/workflows/ci-tests.yml
> +        python -m pip install --editable .
@HGWright What's the reason behind this change?

The lockfile should have installed all the dependencies that are required, hence the `--no-deps`.

Also, isn't the `build_ext` step still required to correctly build the `cython` ?

2025-02-07 13:23 UTC, bjlittle commented on requirements/pypi-core.txt
> +numpy>=2
@HGWright Why is there a min pin for PyPI `numpy` and not `conda`?

2025-02-13 11:23 UTC, HGWright commented on requirements/pypi-core.txt
> +numpy>=2
Just missed it, thanks for catching

2025-02-13 11:25 UTC, HGWright commented on .github/workflows/ci-tests.yml
> +        python -m pip install --editable .
I'm going to be honest, that was the only way I could get it to work with NumPy 2. but now since I have added them back in, it seems to just work anyway now.

2025-02-13 23:26 UTC, bjlittle approved these changes

2025-02-13 23:29 UTC, merged